In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
import pickle
import numpy as np


train_path = '../Data/Output/Chapter6/ex50-train.txt'
val_path = '../Data/Output/Chapter6/ex50-valid.txt'
test_path = '../Data/Output/Chapter6/ex50-test.txt'
model_path = '../Data/Output/Chapter6/model_logisticregression.pickle'

train_fe_path = train_path.replace('.txt', '_features.npy')
val_fe_path = val_path.replace('.txt', '_features.npy')
test_fe_path = test_path.replace('.txt', '_features.npy')

df_train = pd.read_csv(train_path, sep='\t', header=0, index_col='id')
df_valid = pd.read_csv(val_path, sep='\t', header=0, index_col='id')
df_test = pd.read_csv(test_path, sep='\t', header=0, index_col='id')


def get_feature_datas(train_fe_path, val_fe_path, test_fe_path):
    x_train = np.load(train_fe_path, allow_pickle=True)
    x_valid = np.load(val_fe_path, allow_pickle=True)
    x_test = np.load(test_fe_path, allow_pickle=True)
    return x_train, x_valid, x_test


def get_labels():
    # le = preprocessing.LabelEncoder()
    # le.fit(df_train['category'])
    # y = le.transform(df_train['category'])
    # return y
    y_train = df_train["category"]
    y_valid = df_valid["category"]
    y_test = df_test["category"]

    return y_train, y_valid, y_test


x_train, x_valid, x_test = get_feature_datas(
    train_fe_path, val_fe_path, test_fe_path)
y_train, y_valid, y_test = get_labels()
# y_train = get_labels(df_train)
# y_valid = get_labels(df_valid)
# y_test = get_labels(df_test)

# print(type(x_train))
# print(type(y_train))
model = LogisticRegression(random_state=42, max_iter=1000)
trained_model = model.fit(x_train, y_train)
y_pred = trained_model.predict(x_valid)

print(trained_model.predict_proba(x_train))
pickle.dump(model, open(model_path, 'wb'))

[[0.81353513 0.12385026 0.02636456 0.03625004]
 [0.21455866 0.29684922 0.37750515 0.11108697]
 [0.099726   0.77303552 0.06002429 0.06721419]
 ...
 [0.0368152  0.85643469 0.06809514 0.03865496]
 [0.94012012 0.03285388 0.01610331 0.01092269]
 [0.88570551 0.07096919 0.02172735 0.02159795]]
